# Python Datascience

In this jupyter notebook, I collect cool stuff about datascience, following a course on udemy.

Remember to operate the Notebook: 
- esc and H brings up shortcuts
- shift enter: execute a cell
- alt enter: execute a cell and insert a new one below
- object.tab: shows applicable methods (e.g. on a string)

In [3]:
#nice Formatting: 
age = 21
name = 'Oskar'
print('My age is {} and my name is {}.'.format(age, name))
print('My age is {a} and my name is {b}.'.format(a=age, b=name))

My age is 21 and my name is Oskar.
My age is 21 and my name is Oskar.


In [4]:
#Set only accounts for different objects
set([1,1,1,2,2,2,3,3,2,2,1,3,2])

{1, 2, 3}

In [5]:
#list comprehension: 

#long version:
x = [1,2,3,4]
out=[]
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


In [8]:
#short version: 
out = [item**2 for item in x]
print(out)

[1, 4, 9, 16]


In [11]:
#Set documentation string for functions:
def function_name(param='Default_parameter'):
    """
    the documtation string goes here
    """
    return param

In [12]:
#after function, pree shift-tab and you get the signature call of the function :D
function_name()

'Default_parameter'

In [15]:
#lambda expressions: 
#long version:
def times2(var):
    return var*2

#short version:
t = lambda var: var*2

In [18]:
#map and filter act on a list: 
items = [1, 2, 3, 4, 5]
print(list(map(lambda x: x**2, items)))
print(list(filter(lambda x: x%2==0, items)))

[1, 4, 9, 16, 25]
[2, 4]


## NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [5]:
np.array(my_list) #this casts a normal list into an numpy array

array([1, 2, 3])

In [6]:
#now let's have a matrix: 
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#create an array with np.arange function: 
#the values are all integers
#third argument is stepsize
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#zeros-function creates array with zeros: 
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.ones(6)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
#create an identity matrix: 
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [12]:
#with linspace, create a number of evently spaced points:
#third argument is number of points
np.linspace(0,9,5)

array([ 0.  ,  2.25,  4.5 ,  6.75,  9.  ])

Create radom numbers with numpy: 

In [17]:
#one dimensional array with random numbers: 
#from a uniform distribution from 0 to 1
np.random.rand(4)

array([ 0.10815313,  0.13803713,  0.77607922,  0.58426069])

In [18]:
#matrix with random numbers: 
np.random.rand(3,3)

array([[ 0.8300976 ,  0.361814  ,  0.12740746],
       [ 0.23862943,  0.79275234,  0.01369716],
       [ 0.34201823,  0.69930018,  0.90790431]])

In [20]:
#sample from gaussian distribution: 
#normal distribution centered around 0
np.random.randn(2,2)

array([[ 0.25715898,  0.66336495],
       [-0.74316674,  2.98173314]])

In [25]:
#random integers from low to high number: 
#inclusive on low end, exclusive on high end, number of numbers
np.random.randint(1,7,4)

array([5, 4, 3, 1])

useful attributes of arrays: 

In [36]:
#reshape an array into the dimensions you want, 
#total number of elements has to be the same
array1=np.arange(9)

In [37]:
array1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#maximum value in an array: 
array1.max()

0

In [29]:
array1.min()

0

In [30]:
#return index-location of maximum value: 
array1.argmax()

8

In [38]:
#figure out shape of an array: 
array1.shape
#no brackets here, because shape is an attribute

(9,)

In [39]:
#return data type of array: 
array1.dtype

dtype('int64')

In [48]:
array = np.random.randn(3,3)
print(array)
print(array.shape)
print(array.min())
print(array.argmin())
print(array.max())
print(array.argmax())

[[ 1.47694337  0.61030579  1.35463488]
 [-0.4368715   0.89856528 -1.02850678]
 [-0.31693054  1.39371159 -0.06835957]]
(3, 3)
-1.0285067826
5
1.47694336744
0


Indexing and Selection

In [50]:
#Return array elements similar to lists: 
#array[index]
#array[start:end:step]

#Set multiple values to one value: 
#array[0:3] = value

#Important: 
#editing a slice of an array edits the original array as well!
#this is done for efficient memory use with large datasets.
#therefore, to copy an array, use array.copy() -method.

In [51]:
#Grab elements in 2D-Arrays: 
#Double Bracket notation: Row, Colum
#array[row][colum] #returns element

#Comma-Single-Bracket Notation
#array[row, colum]

In [72]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1][1])
#print(array[1, 2])

TypeError: 'list' object is not callable

In [64]:
#Slice a matrix: 
array[:2]

[[1, 2, 3], [4, 5, 6]]